language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=4.0 WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=1

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit

notifications:
  slack:
    secure: Uc7oPINbCEX+Y+jUwqkiVIxX1o83FGr+m0fvRPkgDcwsT2RV0mVlMeYSRtkmk4leW0kPWW1ybBgdAZZMhXrtsDAEjCjhd4KbvJXJdBqS7m4/ZKjEB0HU39oYd8o3XFxMx1i4ZEQxx6Gc/NGPzlo+p/0PmYN7vrc8g8L7NcMK7cy+Hx9Td9whY/a7/1CtsDB13697kneDgTY6ddIewFYJPlHMPW3m5RkqVqcBdcM3f6ZKqBOkjSruniX/VYtjeeaRQkcTOoYvYSEF3CA2rEd4H8ECrcVcR8YsYNruvO0RlsuZGwdEj8Uxp2H+XhSj+KJ/naaA3h1gZ5uA+OPiCfKKeHYFXoLHffexeSKcH5PHrOJq4Two8Qxxe4girufV1N4PtRg678amjS1r5u0hoJItFom59HNwmMqGYcP+wEztQLitNT3zYAA4xCyw60BHJH2w5n8bwU1Pjob2qErE0zY6++TrpaXO1wXnnCA2BriTcxLeJm4aj85tpnr2SZgRuZAunKUyQjZSmFSkFc8qOG9e4DFCx+Dasu3aB1D9zo1Fmch/8fUsSssSkX34vvHHVAoSFrhX5nIKTfpTQ/LMnIgslth5sQiW0YC7uA9IiqVKXaH3P1dhBMLPo7gKpENJzLFiKE58Rh2/eOpwSwhWXGOdCj9ZTdR9atCtteb+qCJWUHs=
